# Generated by Django 4.0.2 on 2023-04-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_name', models.CharField(max_length=50)),
                ('u_mailid', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=25)),
                ('hobby', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_status', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('reqreceiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='login.user')),
                ('reqsender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('msgreceiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgre', to='login.user')),
                ('msgsender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msge', to='login.user')),
            ],
        ),
    ]
