# Generated by Django 4.1.7 on 2023-04-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_dob_alter_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.user')),
                ('users1', models.ManyToManyField(null=True, to='login.user')),
            ],
        ),
    ]
