# Generated by Django 4.0.2 on 2023-04-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends1',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friends1',
            name='users1',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friends1',
        ),
    ]
