# Generated by Django 4.0.2 on 2023-04-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_friends1_current_user_remove_friends1_users1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Req',
        ),
    ]
